version: '3'
services:
  db: 
    image: mongo:4.2.8
    container_name: db
    ports:
      - '4002:27017'
    restart: always

  video-storage:
    image: video-storage
    build:
      context: ./minio-storage
      dockerfile: Dockerfile
    container_name: video-storage 
    ports:
      - '4000:80'
    environment:
      - PORT=80
      - HOST=harbor.keymamo.com
      - ACCESS_KEY=ERZ0qmDYO7zVFCmj
      - SECRET_KEY=RZw59wG1KRXR5ry6FpzBGnVysjLPZJCa
    restart: 'no'

  video-streaming:
    image: video-streaming   
    build:
      context: ./video-streaming 
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    ports:
      - '4001:80'
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: 'no'
  
  history:
    image: history 
    build:
      context: ./history
      dockerfile: Dockerfile-dev 
    container_name: history 
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src/:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: "no"
  
  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always