# FROM node:16.20-alpine 

# WORKDIR /usr/src/app
# COPY package*.json ./

# CMD npm config set cache-min 9999999 && \
#     npm install && \
#     npx wait-port rabbit:5672 && \
#     npm run start:dev

FROM node:16.20-alpine 
WORKDIR /usr/src/app 
COPY package*.json ./
ENV PORT=3000
RUN npm install 
COPY ./src ./src
# COPY ./videos ./videos 
CMD npx wait-port rabbit:5672 && npm run start:dev